### ISSUE TITLE
Stackage nightly build failure

### ISSUE THREAD

**Issue by lwm** [dredozubov/schematic#1]
```
src/Data/Schematic.hs:25:1: error:
    Failed to load interface for ‘Data.Schematic.Migration’
    Use -v to see a list of the files searched for.
```

**Comment by dredozubov** [comment]
@lwm Thanks for telling me about it. How can I check if the issue persists with the latest release? The library is experimental and I see no point in having old versions on stackage.

**Comment by dredozubov** [comment]
fixed
