### ISSUE TITLE
Overabundance of singleton values

### ISSUE THREAD

**Issue by int-index** [dredozubov/schematic#2]
Looking at this definition

```
data instance Sing (jp :: PathSegment) where
  SKey :: (KnownSymbol k, Known (Sing k)) => Sing (k :: Symbol) -> Sing ('Key k)
  SIx :: (KnownNat n, Known (Sing n)) => Sing (n :: Nat) -> Sing ('Ix n)
```

you can see that every constructor stores three (!) singletons. In case of `SKey`:

1. one in the `KnownSymbol k` dictionary
2. one in the `Known (Sing k)` dictionary
3. one as `Sing (k :: Symbol)`.

And all of those singletons are for the same type variable `k`. And it's not hard to convert between them because `Sing` for `Symbol` is a wrapper around `KnownSymbol`:

1. `withKnownSymbol` can be used to get `KnownSymbol k` from `Sing k`
2. `SSym` can be used to get `Sing k` from `KnownSymbol k` 
3. `withSingI` can be used to get `SingI k` from `Sing k`
4. `sing` can be used to get `Sing k` from `SingI k`
5. no action required to get `Known (Sing k)` from `SingI k` (there's a global instance for this)
6. `known` can be used to get `Sing k` from `Known (Sing k)`.

So it's not necessary to store all three representations in this data structure. I propose to remove the unnecessary constraints:

```
data instance Sing (jp :: PathSegment) where
  SKey :: Sing (k :: Symbol) -> Sing ('Key k)
  SIx :: Sing (n :: Nat) -> Sing ('Ix n)
```

This is in line with what `singletons` generate by default using TemplateHaskell, and you retain full expressive power. The advantages of doing this is that

* removing redundancy simplifies reasoning
* memory layout is cleaner

A minor disadvantage is that you'd need to invoke the conversion functions I mentioned above, and this is a price that you've got to pay at pattern-matching site. But with the current setup there's the same price you've got to pay at construction site (if you've got only `Sing k`, you'd need to conjure up `KnownSymbol k` and `Known (Sing k)` out of it in order to construct `SKey`). So all in all, there's nothing to lose.

This refactoring applies to other definitions in the library as well.

**Comment by dredozubov** [comment]
Good catch! I'm aware of the issue and it's mostly artifacts by now. I expect I'll fix this issue(and a few more, library clearly lacks lenses e.g.) somewhere around the release of ghc 8.2.

I wasn't aware of `SSym` for some reason, so I appreciate your explanation!

**Comment by dredozubov** [comment]
fixed in master
